### ISSUE TITLE
Installing ansible coda package also gets me ansible-base==2.10.3 pip package

### ISSUE THREAD

**Issue by calebmarchent** [conda-forge/ansible-feedstock#70]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

Sounds crazy, so if anything, I would appreciate someone telling me this isn't happening for them.
Since conda ansible 2.10, if I create a clean environment and install only ansible, I get a pip package installed with ansible-base==2.10.3... while I know conda does support pip, this seems like a bug. 
Installing a version less than 2.10 (2.9.x) this does not happen.

<br/>
Environment (<code>conda list</code>):

Ubuntu Linux 18.04 (LTS) x86
conda 4.9.2

<details>

```
$ conda env export
name: test
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - ansible=2.10.5=py36h5fab9bb_0
  - appdirs=1.4.4=py_0
  - bcrypt=3.2.0=py36h7b6447c_0
  - boto=2.49.0=py36_0
  - brotlipy=0.7.0=py36h27cfd23_1003
  - brotlipy=0.7.0=py36h27cfd23_1003
  - ca-certificates=2020.12.8=h06a4308_0
  - certifi=2020.12.5=py36h06a4308_0
  - cffi=1.14.4=py36h261ae71_0
  - chardet=4.0.0=py36h06a4308_1003
  - cryptography=3.3.1=py36h3c74f83_0
  - decorator=4.4.2=py_0
  - dogpile.cache=0.9.2=pyh9f0ad1d_0
  - httplib2=0.18.1=pyh9f0ad1d_0
  - idna=2.10=py_0
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - iso8601=0.1.13=py36_1
  - jinja2=2.11.2=py_0
  - jmespath=0.10.0=py_0
  - jsonpatch=1.28=pyhd3eb1b0_0
  - jsonpointer=2.0=py_0
  - keystoneauth1=4.3.0=pyhd8ed1ab_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - markupsafe=1.1.1=py36h7b6447c_0
  - munch=2.5.0=py_0
  - ncurses=6.2=he6710b0_1
  - netifaces=0.10.9=py36h8c4c3a4_1003
  - openssl=1.1.1i=h27cfd23_0
  - openstacksdk=0.52.0=py36h5fab9bb_0
  - os-service-types=1.7.0=pyh9f0ad1d_0
  - paramiko=2.7.2=py_0
  - pbr=5.5.1=py_0
  - pip=20.3.3=py36h06a4308_0
  - pycparser=2.20=py_2
  - pynacl=1.4.0=py36h7b6447c_1
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pysocks=1.7.1=py36h06a4308_0
  - python=3.6.12=hcff3b4d_2
  - python_abi=3.6=1_cp36m
  - pyyaml=5.3.1=py36h7b6447c_1
  - readline=8.0=h7b6447c_0
  - requests=2.25.1=pyhd3eb1b0_0
  - requestsexceptions=1.4.0=py_0
  - setuptools=51.0.0=py36h06a4308_2
  - six=1.15.0=py36h06a4308_0
  - sqlite=3.33.0=h62c20be_0
  - stevedore=3.3.0=py36h5fab9bb_0
  - tk=8.6.10=hbc83047_0
  - urllib3=1.26.2=pyhd3eb1b0_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zipp=3.4.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - ansible-base==2.10.3



```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
$ conda info

     active environment : test
    active env location : /home/calebm/miniconda3/envs/test
            shell level : 1
       user config file : /home/calebm/.condarc
 populated config files : /home/calebm/.condarc
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __cuda=11.0=0
                          __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/calebm/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/calebm/miniconda3/pkgs
                          /home/calebm/.conda/pkgs
       envs directories : /home/calebm/miniconda3/envs
                          /home/calebm/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.5 Linux/5.4.0-53-generic ubuntu/18.04.5 glibc/2.27
                UID:GID : ----:---
             netrc file : None
           offline mode : False
```
</details>

**Comment by rookwood101** [comment]
I can confirm this issue. It looks like it might have been introduced at this commit: https://github.com/conda-forge/ansible-feedstock/commit/ecce26ecd88a99d6c3dcf11f87efe6077bc6c29f

There are a couple of reasons why I think this is incorrect behaviour:
* conda packages ought to correspond to one pip package IMO
* there is already a ansible-base conda package, which this package should depend on, if ansible-base is a required dependency of ansible.

**Comment by calebmarchent** [comment]
Thanks @rookwood101 I have done a test with `conda install ansible-base` run before installing before `conda install ansible` sure enough I first get `ansible-base==2.10.4` but on installing ansible I now have pip package `ansible-base==2.10.3`?

@tschoonj please can you confirm if this behaviour is intended?

**Comment by tschoonj** [comment]
This is absolutely intended. Ansible got split up in 2.10 into a base package and separate collections. To ensure you have access to all features you did before, without manually installing the collections, I had to install the unusable package, which depends on the base package and brings in the collections as well.

**Comment by tschoonj** [comment]
I wasn't aware that an `ansible-base` feedstock had been created recently. I will modify the recipe accordingly to ensure it depends on that.

**Comment by calebmarchent** [comment]
> I wasn't aware that an `ansible-base` feedstock had been created recently. I will modify the recipe accordingly to ensure it depends on that.

Can I propose that this issue remains open until that is done?
